export const meta = {
  name: 'arxiv-nightly-ideation-2026-09-11',
  description: 'Ideate project/startup/youtube/demo ideas from 30 fresh arXiv papers in batches of 5',
  phases: [
    { title: 'Ideate' },
  ],
}

const BATCHES = [
  [
    {id:'2609.05165v1',cat:'cs.LG',title:'Conformal Prediction for Offensive Security'},
    {id:'2609.05774v1',cat:'cs.AI',title:'Inference-Time Graph Engineering for Multi-Agent LLM Workflows'},
    {id:'2609.01188v1',cat:'cs.CL',title:'PersuaRL: Reinforcement Learning-Driven Multi-Expert Selection for Persuasive Dialogue Generation in Insurance'},
    {id:'2608.17960v1',cat:'cs.CR',title:'COMA: A Compositional Misleading Attack Class on Security-RAG, and a Causal Counterfactual Defense'},
    {id:'2607.02150v1',cat:'cs.DS',title:'Tight Lower Bounds for the Multi-Secretary Problem via Bellman Certificates'},
  ],
  [
    {id:'2608.20644v1',cat:'math.CO',title:'A One-Third Bound for the Maker--Breaker Degree Game'},
    {id:'2608.10128v1',cat:'math.OC',title:'Geometric optimization problems generated by plane curves'},
    {id:'2608.09368v2',cat:'math.PR',title:"A proof of Ross's conjecture for two-site moving-target search"},
    {id:'2608.00778v1',cat:'math.NT',title:'The Minimal Degree of Salem Numbers with Negative Trace'},
    {id:'2308.11294v1',cat:'q-fin.PM',title:'Network Momentum across Asset Classes'},
  ],
  [
    {id:'2307.01814v2',cat:'q-fin.TR',title:'Option Market Making via Reinforcement Learning'},
    {id:'2602.07667v2',cat:'econ.EM',title:'Fast Response or Silence: Conversation Persistence in an AI-Agent Social Network'},
    {id:'2607.22951v1',cat:'stat.ML',title:'Modeling Memory-Dependent Reliability of LLMs: A Hidden Markov Model'},
    {id:'2602.17820v2',cat:'q-bio.NC',title:'Scaling and tuning to criticality in resting-state human magnetoencephalography'},
    {id:'2504.16479v1',cat:'q-bio.BM',title:'The Dance of Atoms-De Novo Protein Design with Diffusion Model'},
  ],
  [
    {id:'2409.02143v3',cat:'q-bio.GN',title:'MLOmics: Cancer Multi-Omics Database for Machine Learning'},
    {id:'2603.03237v1',cat:'q-bio.QM',title:'Topology of Multi-species Localization'},
    {id:'2510.22220v1',cat:'q-bio.PE',title:'Evolution of the lexicon: a probabilistic point of view'},
    {id:'2606.11730v1',cat:'physics.chem-ph',title:'Tailoring soft cavities for robust molecular strong coupling'},
    {id:'2606.14904v1',cat:'cond-mat.soft',title:'Many-body activity emerging in a monolayer of air-fluidized hollow pentagons'},
  ],
  [
    {id:'2607.22047v1',cat:'cond-mat.stat-mech',title:'Multiplicity of Stable Attractors in Disordered Neural Models'},
    {id:'2604.05860v1',cat:'physics.soc-ph',title:'Symmetry-Breaking and Hysteresis in a Duplex Voter Model'},
    {id:'2607.02766v1',cat:'cs.DS',title:'On the Cost of Non-Adaptivity in Matroid Prophet Inequalities'},
    {id:'2604.05714v1',cat:'physics.soc-ph',title:'Publish and Perish: How AI-Accelerated Writing Without Proportional Verification Investment Degrades Scientific Knowledge'},
    {id:'2606.14661v1',cat:'cond-mat.soft',title:'Percolation of a rod-like particle in a static bed of spheres: trapping and passing'},
  ],
  [
    {id:'2307.01816v1',cat:'q-fin.TR',title:'Over-the-Counter Market Making via Reinforcement Learning'},
    {id:'2602.16584v1',cat:'q-bio.NC',title:'The Representational Alignment Hypothesis: Evidence for and Consequences of Invariant Semantic Structure Across Embedding Modalities'},
    {id:'2603.03604v1',cat:'q-bio.QM',title:'Tracking Feral Horses in Aerial Video Using Oriented Bounding Boxes'},
    {id:'2608.20860v1',cat:'math.CO',title:'A cube-root phase transition in tree-child networks and the enumeration threshold for galled networks'},
    {id:'2510.25085v1',cat:'q-bio.PE',title:'Explorations of Epidemiological Dynamics across Multiple Population Hubs'},
  ],
]

const SCHEMA = {
  type: 'object',
  properties: {
    ideas: {
      type: 'array',
      items: {
        type: 'object',
        properties: {
          type: { type: 'string', enum: ['project', 'startup', 'youtube', 'demo'] },
          title: { type: 'string' },
          paper: { type: 'string' },
          pitch: { type: 'string' },
          cool: { type: 'number' },
          buildable: { type: 'number' },
          discussion: { type: 'number' },
          discussion_why: { type: 'string' },
          tags: { type: 'array', items: { type: 'string', enum: ['betting','poker','sports','games','gambling','decision-theory','ai','math','bio','physics','econ','whimsy'] } },
        },
        required: ['type', 'title', 'paper', 'pitch', 'cool', 'buildable', 'discussion', 'discussion_why', 'tags'],
      },
    },
  },
  required: ['ideas'],
}

function batchPrompt(batch) {
  const list = batch.map(p => `- ${p.id} [${p.cat}] ${p.title}`).join('\n')
  return `You're mining fresh arXiv papers for cool project/startup/YouTube-video/demo ideas. Here are 5 papers (fetch each abstract from arxiv.org/abs/<id> if you need more than the title to judge the actual result):
${list}

For each paper, propose 2-4 concrete ideas. Tag each idea's type: project (something to build/ship), startup (a business), youtube (a video/explainer concept), or demo (an interactive toy/visualization). Score each on:
- cool (1-10): how cool/shareable is this
- buildable (1-10): how buildable TONIGHT as a single self-contained HTML file with no backend (prefer interactive visualizations, playable toys, mind-bending demos)
- discussion (1-10): how much would this spark debate on a betting/poker/sports/games Discord server — blend (i) debate/relatability, (ii) fit with betting/poker/sports/games/gambling/decision-theory, (iii) surprise ("wait, really?"), (iv) whimsy (weird-and-delightful)
- discussion_why: one sentence naming which axis it wins on
- tags: pick from betting, poker, sports, games, gambling, decision-theory, ai, math, bio, physics, econ, whimsy

Return via the structured schema.`
}

phase('Ideate')
const results = await parallel(BATCHES.map((batch, i) =>
  () => agent(batchPrompt(batch), { label: `batch-${i + 1}`, phase: 'Ideate', schema: SCHEMA })
))

const allIdeas = results.filter(Boolean).flatMap(r => r.ideas)
log(`${allIdeas.length} ideas surfaced across ${BATCHES.length} batches`)
return { ideas: allIdeas }
