export const meta = {
  name: 'arxiv-nightly-ideation-2026-08-16',
  description: 'Ideate project/startup/youtube/demo ideas from 30 fresh arXiv papers in batches of 5',
  phases: [
    { title: 'Ideate' },
  ],
}

const BATCHES = [
  [
    {id:'2608.08158v1',cat:'cs.LG',title:"A Unified Framework for Dynamic Reward Shaping in Reinforcement Learning"},
    {id:'2608.09088v1',cat:'cs.AI',title:"A Multi-Scale Temporal Framework with Dynamic Fusion for EEG-Based Emotion Recognition"},
    {id:'2608.03573v2',cat:'cs.CL',title:"SFT Conflicts, RL Coexists: A Theoretical and Empirical Analysis of Multi-Task Learning for LLMs"},
    {id:'2607.18770v1',cat:'cs.CR',title:"GLID: Gated Local Intrinsic Dimension Repairs the Blind Spots of Face-Forgery Detectors"},
    {id:'2606.11760v1',cat:'cs.DS',title:"A Fast Gaussian Mechanism under Continual Observation, with Applications"},
  ],
  [
    {id:'2607.23071v1',cat:'math.CO',title:"Spectrality of Moran-Type Measures Generated by Two-Element and Three-Element Digit Sets"},
    {id:'2607.12286v1',cat:'math.OC',title:"Structured Preconditioning in Affine-Invariant Geometry: Projection, Certificates, and Kronecker Separation"},
    {id:'2607.09547v1',cat:'math.PR',title:"High-Dimensional Interpolators Can Be Fragile: Heavy Tails and High-Dimensional Large Deviations"},
    {id:'2607.00088v1',cat:'math.NT',title:"Central isogenies and conjugacy classes in reductive groups"},
    {id:'2311.15247v1',cat:'q-fin.PM',title:"Information Content of Financial Youtube Channel: Case Study of 3PROTV and Korean Stock Market"},
  ],
  [
    {id:'2309.13648v2',cat:'q-fin.TR',title:"Don't Let MEV Slip: The Costs of Swapping on the Uniswap Protocol"},
    {id:'2602.01417v1',cat:'econ.EM',title:"Identification and Estimation in Fuzzy Regression Discontinuity Designs with Covariates"},
    {id:'2607.02510v1',cat:'stat.ML',title:"Online Safety Monitoring for LLMs"},
    {id:'2602.13368v3',cat:'q-bio.NC',title:"The Influence of Width Ratios on Structural Beauty in Male Faces"},
    {id:'2505.08850v1',cat:'q-bio.BM',title:"High-throughput Screening of the Mechanical Properties of Peptide Assemblies"},
  ],
  [
    {id:'2410.19922v1',cat:'q-bio.GN',title:"Disentangling Genotype and Environment Specific Latent Features for Improved Trait Prediction using a Compositional Autoencoder"},
    {id:'2602.23269v2',cat:'q-bio.QM',title:"An Active Learning Framework for Data-Efficient, Human-in-the-Loop Enzyme Function Prediction"},
    {id:'2511.00138v1',cat:'q-bio.PE',title:"Incentives for self-isolation based on incidence rather than prevalence could help to flatten the curve: a modelling study"},
    {id:'2605.18473v2',cat:'physics.chem-ph',title:"Accelerating charging dynamics of electric double-layer capacitors"},
    {id:'2605.24987v1',cat:'cond-mat.soft',title:"DNA end tethering through break-induced DNA--protein condensation"},
  ],
  [
    {id:'2606.27486v1',cat:'cond-mat.stat-mech',title:"Jarzynski equality for counterwork under reversed memory-filtered driving"},
    {id:'2603.28949v2',cat:'physics.soc-ph',title:"The Planetary Cost of AI Acceleration: A Thermodynamic Outlook on Four Possible Paths Forward"},
    {id:'2608.08126v1',cat:'cs.LG',title:"Accurate Ensembles, Fragile Narratives: Multi-Scale Stacking and a Fidelity Audit of LLM-Generated Explanations for Credit Risk"},
    {id:'2607.18659v1',cat:'cs.CR',title:"Broken Gates: Re-evaluating Web Bot Defenses in the Age of LLM Agents"},
    {id:'2606.11437v1',cat:'cs.DS',title:"The Power of Test-Time Training for Approximate Sampling"},
  ],
  [
    {id:'2607.22968v2',cat:'math.CO',title:"Isoperimetric-Combinatorial Bounds for Range-Controlled Matchings and Quasi-Interpolation from Scattered Data"},
    {id:'2607.12134v1',cat:'math.OC',title:"The Certification Limits of KS-Type Layer Relaxations: A Square-Root Ceiling and Its Breakdown"},
    {id:'2607.09228v1',cat:'math.PR',title:"Central Limit Theorems for Functionals of Persistence Diagrams in Germ-Grain Random Set Models with Applications to Goodness-of-Fit Testing"},
    {id:'2606.31783v1',cat:'math.NT',title:"Construction of Generically Ordinary Families of Hyperelliptic Curves"},
    {id:'2602.22289v2',cat:'q-bio.QM',title:"What Topological and Geometric Structure Do Biological Foundation Models Learn? Evidence from 141 Hypotheses"},
  ],
]

const SCHEMA = {
  type: 'object',
  properties: {
    ideas: {
      type: 'array',
      items: {
        type: 'object',
        properties: {
          type: { type: 'string', enum: ['project', 'startup', 'youtube', 'demo'] },
          title: { type: 'string' },
          paper: { type: 'string' },
          pitch: { type: 'string' },
          cool: { type: 'number' },
          buildable: { type: 'number' },
        },
        required: ['type', 'title', 'paper', 'pitch', 'cool', 'buildable'],
      },
    },
  },
  required: ['ideas'],
}

function batchPrompt(batch) {
  const list = batch.map(p => `- ${p.id} [${p.cat}] ${p.title}`).join('\n')
  return `You're mining fresh arXiv papers for cool project/startup/YouTube-video/demo ideas. Here are 5 papers (fetch each abstract from arxiv.org/abs/<id> if you need more than the title to judge the actual result):
${list}

For each paper (or combination of papers if a crossover idea is stronger), propose 2-4 ideas total across the batch, each tagged with one type:
- project: something buildable as a tool/library/service
- startup: a business angle
- youtube: a video/explainer concept
- demo: an interactive web toy that lets someone FEEL the paper's actual mathematical/scientific result

Score each idea 1-10 on:
- cool: how cool/shareable/wow is it
- buildable: how buildable TONIGHT as a single self-contained HTML file (canvas/svg/d3/three.js via CDN, no backend, no build step) — demos should score highest here if they only need client-side math/sim

Ground every idea in the paper's actual claimed result, not just its title vibe. Return via the schema.`
}

phase('Ideate')
const results = await parallel(BATCHES.map((batch, i) => () =>
  agent(batchPrompt(batch), { label: `batch-${i + 1}`, phase: 'Ideate', schema: SCHEMA })
))

const allIdeas = results.filter(Boolean).flatMap(r => r.ideas)
log(`${allIdeas.length} ideas generated across ${BATCHES.length} batches`)
return { ideas: allIdeas }
