export const meta = {
  name: 'arxiv-nightly-ideation-2026-08-30',
  description: 'Ideate project/startup/youtube/demo ideas from 30 fresh arXiv papers in batches of 5, scored on cool/buildable/discussion',
  phases: [
    { title: 'Ideate' },
  ],
}

const BATCHES = [
  [
    {id:'2608.22354v2',cat:'cs.AI',title:'SANE: State Anomaly Neutralization for Stable Extreme-Context Delta-Rule Models'},
    {id:'2607.20646v1',cat:'math.PR',title:'The Independence-Preserving Property and Planar Web Geometry'},
    {id:'2409.18156v1',cat:'q-bio.GN',title:'A novel application of Shapley values for large multidimensional time-series data'},
    {id:'2608.02274v1',cat:'cs.CR',title:'A Multi-Objective AutoML-based Efficient Intrusion Detection System for EV Charging Networks'},
    {id:'2608.22387v1',cat:'cs.AI',title:'Self-Supervised Graph Representation Learning for In-The-Wild Wearable and Smartphone based Emotion Recognition'},
  ],
  [
    {id:'2605.30165v1',cat:'physics.chem-ph',title:'Tunneling phase diagram: A machine-learning framework for multidimensional kinetic isotope effects'},
    {id:'2607.06942v1',cat:'cond-mat.stat-mech',title:'Invariant Measures for Soliton Systems Generated by Mealy Automata'},
    {id:'2310.02163v3',cat:'q-fin.PM',title:'Navigating Uncertainty in ESG Investing'},
    {id:'2604.00674v1',cat:'physics.soc-ph',title:'Managing the Mismatch: The Role of Flexibility on the Path to a Carbon-Neutral Energy System'},
    {id:'2307.15599v2',cat:'q-fin.TR',title:'Understanding the worst-kept secret of high-frequency trading'},
  ],
  [
    {id:'2608.22388v1',cat:'cs.AI',title:'ProBel: Propaganda Detection with Techniques, Spans, and Explanations'},
    {id:'2607.20818v2',cat:'math.PR',title:'Self-Balancing Sequential Sampling: Fast Convergence with Controlled Predictability'},
    {id:'2603.01396v2',cat:'q-bio.QM',title:'HarmonyCell: Automating Single-Cell Perturbation Modeling under Semantic and Distribution Shifts'},
    {id:'2606.00319v1',cat:'cond-mat.soft',title:'Impact of viscoelastic polymer solution droplets on a granular bed'},
    {id:'2510.23360v1',cat:'q-bio.PE',title:'Effect of intratumor heterogeneity in managing the go-or-grow dichotomy of cancer cells: a game theory approach'},
  ],
  [
    {id:'2309.00626v1',cat:'q-fin.TR',title:'An Ensemble Method of Deep Reinforcement Learning for Automated Cryptocurrency Trading'},
    {id:'2510.26115v2',cat:'q-bio.PE',title:'Quenched coalescent for diploid population models with selfing and overlapping generations'},
    {id:'2510.24602v1',cat:'q-bio.PE',title:'Learning to generalize in evolution through annealed population heterogeneity'},
    {id:'2608.06225v1',cat:'math.CO',title:'Noncrossing Combinatorics, the Full Twist, and Decategorification of Knot Invariants'},
    {id:'2607.06822v1',cat:'cond-mat.stat-mech',title:"A neural-network Maxwell's demon learns cold damping for work extraction"},
  ],
  [
    {id:'2308.00013v1',cat:'q-fin.TR',title:"Bitcoin Gold, Litecoin Silver: An Introduction to Cryptocurrency's Valuation and Trading Strategy"},
    {id:'2606.22520v1',cat:'cs.DS',title:'Submodular Welfare Maximization with Budget Constraints in the Random-Order Model'},
    {id:'2608.06248v1',cat:'math.CO',title:'On uniform eventowns'},
    {id:'2608.06358v1',cat:'math.CO',title:'Universality in random graphs via optimal linking systems: trees and beyond'},
    {id:'2310.02014v1',cat:'q-fin.PM',title:'Utility-based acceptability indices'},
  ],
  [
    {id:'2607.11408v1',cat:'math.NT',title:'The combinatorics of sector renormalization'},
    {id:'2605.31355v5',cat:'cond-mat.soft',title:'Spontaneous flows and interfacial instabilities in oxygen-sensitive living active matter'},
    {id:'2606.22851v1',cat:'cs.DS',title:'Faster enumeration of primes'},
    {id:'2603.29833v1',cat:'physics.soc-ph',title:'Copy-Spread-Annihilate Dynamics in Degree-Assortative Networks'},
    {id:'2308.01112v1',cat:'q-fin.TR',title:'Quantitative statistical analysis of order-splitting behaviour of individual trading accounts'},
  ],
];
const SCHEMA = {
  type: 'object',
  properties: {
    ideas: {
      type: 'array',
      items: {
        type: 'object',
        properties: {
          type: { type: 'string', enum: ['project', 'startup', 'youtube', 'demo'] },
          title: { type: 'string' },
          paper: { type: 'string' },
          pitch: { type: 'string' },
          cool: { type: 'number' },
          buildable: { type: 'number' },
          discussion: { type: 'number' },
          discussion_why: { type: 'string' },
          tags: { type: 'array', items: { type: 'string', enum: ['betting','poker','sports','games','gambling','decision-theory','ai','math','bio','physics','econ','whimsy'] } },
        },
        required: ['type', 'title', 'paper', 'pitch', 'cool', 'buildable', 'discussion', 'discussion_why', 'tags'],
      },
    },
  },
  required: ['ideas'],
}

function batchPrompt(batch) {
  const list = batch.map(p => `- ${p.id} [${p.cat}] ${p.title}`).join('\n')
  return `You're mining fresh arXiv papers for cool project/startup/YouTube-video/demo ideas. Here are 5 papers (fetch each abstract from arxiv.org/abs/<id> if you need more than the title to judge the actual result):
${list}

For each paper (or combination of papers if a crossover idea is stronger), propose 2-4 ideas total across the batch, each tagged with one type:
- project: something buildable as a tool/library/service
- startup: a business angle
- youtube: a video/explainer concept
- demo: an interactive web toy that lets someone FEEL the paper's actual mathematical/scientific result

Score each idea 1-10 on:
- cool: how cool/shareable/wow is it
- buildable: how buildable TONIGHT as a single self-contained HTML file (canvas/svg/d3/three.js via CDN, no backend, no build step) -- demos should score highest here if they only need client-side math/sim
- discussion: how much it would spark debate on a betting/poker/sports/games Discord server -- blend (i) debate/relatability, (ii) fit with betting/poker/sports/games/gambling/decision-theory, (iii) surprise ("wait, really?"), (iv) whimsy (weird-and-delightful)

Also give a one-line discussion_why explaining the discussion score, and tag each idea with 1-3 tags from this exact list: betting, poker, sports, games, gambling, decision-theory, ai, math, bio, physics, econ, whimsy.

Ground every idea in the paper's actual claimed result, not just its title vibe. Return via the schema.`
}

phase('Ideate')
const results = await parallel(BATCHES.map((batch, i) => () =>
  agent(batchPrompt(batch), { label: `batch-${i + 1}`, phase: 'Ideate', schema: SCHEMA })
))

const allIdeas = results.filter(Boolean).flatMap(r => r.ideas)
log(`${allIdeas.length} ideas generated across ${BATCHES.length} batches`)
return { ideas: allIdeas }
